"""drop redundant id index

Revision ID: 1371b191feb4
Revises: 42a8e33353c5
Create Date: 2026-05-09 22:03:23.183457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1371b191feb4'
down_revision: Union[str, Sequence[str], None] = '42a8e33353c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortened_urls_id'), table_name='shortened_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shortened_urls_id'), 'shortened_urls', ['id'], unique=False)
    # ### end Alembic commands ###
