"""create shortened urls table

Revision ID: 42a8e33353c5
Revises: 
Create Date: 2026-05-09 21:59:45.255049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a8e33353c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortened_urls_id'), 'shortened_urls', ['id'], unique=False)
    op.create_index(op.f('ix_shortened_urls_short_code'), 'shortened_urls', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortened_urls_short_code'), table_name='shortened_urls')
    op.drop_index(op.f('ix_shortened_urls_id'), table_name='shortened_urls')
    op.drop_table('shortened_urls')
    # ### end Alembic commands ###
