"""add optional owner to shortened urls

Revision ID: aa604fc3442a
Revises: 059a9c8f7a59
Create Date: 2026-05-10 03:23:08.173226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa604fc3442a'
down_revision: Union[str, Sequence[str], None] = '059a9c8f7a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_urls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shortened_urls_user_id'), 'shortened_urls', ['user_id'], unique=False)
    op.create_foreign_key(None, 'shortened_urls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortened_urls', type_='foreignkey')
    op.drop_index(op.f('ix_shortened_urls_user_id'), table_name='shortened_urls')
    op.drop_column('shortened_urls', 'user_id')
    # ### end Alembic commands ###
